### ISSUE TITLE
项目运行报错啊

### ISSUE THREAD

**Issue by icaurs** [kongqw/KqwSerialPortDemo#2]
08-17 17:46:21.448 11850-11850/qingwei.kong.kqwserialportdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: qingwei.kong.kqwserialportdemo, PID: 11850
                                                                                java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/qingwei.kong.kqwserialportdemo-1/base.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_dependencies_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_0_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_1_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_2_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_3_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_4_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_5_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_6_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_7_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_8_apk.apk", zip file "/data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/qingwei.kong.kqwserialportdemo-1/lib/arm64, /data/app/qingwei.kong.kqwserialportdemo-1/base.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/qingwei.kong.kqwserialportdemo-1/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "libserial_port.so"
                                                                                    at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                                                                                    at java.lang.System.loadLibrary(System.java:1567)
                                                                                    at qingwei.kong.serialportlibrary.SerialPort.<clinit>(SerialPort.java:86)
                                                                                    at qingwei.kong.kqwserialportdemo.MyApplication.getSerialPort(MyApplication.java:25)
                                                                                    at qingwei.kong.kqwserialportdemo.SerialPortActivity.onCreate(SerialPortActivity.java:101)
                                                                                    at qingwei.kong.kqwserialportdemo.MainActivity.onCreate(MainActivity.java:16)
                                                                                    at android.app.Activity.performCreate(Activity.java:6912)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2870)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2978)
                                                                                    at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by kongqw** [comment]
已重构

**Comment by palorotolo** [comment]
# main(1)

java.lang.UnsatisfiedLinkError

dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/cn.weishu.cabinet-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.weishu.cabinet-1/lib/arm64, /data/app/cn.weishu.cabinet-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libserial_port.so"


java.lang.Runtime.loadLibrary(Runtime.java:367)
--
2 java.lang.System.loadLibrary(System.java:1076)
3 com.epton.sdk.SerialPort.<clinit>(Unknown Source)
4 com.epton.sdk.a.d.a(Unknown Source)
5 com.epton.sdk.port.PortController.init(Unknown Source)
6 cn.weishu.cabinet.util.PortManager.init(PortManager.java:43)
7 cn.weishu.cabinet.app.CabApplication$onCreate$1.run(CabApplication.kt:15)
8 android.os.Handler.handleCallback(Handler.java:815)
9 android.os.Handler.dispatchMessage(Handler.java:104)
10 android.os.Looper.loop(Looper.java:207)
11 android.app.ActivityThread.main(ActivityThread.java:5765)
12 java.lang.reflect.Method.invoke(Native Method)
13 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
14 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
