### ISSUE TITLE
Android手机获取不到String[] mDevices = serialPortFinder.getAllDevicesPath();，mDevices大小为0

### ISSUE THREAD

**Issue by chuncainiao** [kongqw/KqwSerialPortDemo#31]
java.io.FileNotFoundException: /proc/tty/drivers: open failed: EACCES (Permission denied)
 W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:496)
W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:159)
 W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:115)
 W/System.err:     at java.io.FileReader.<init>(FileReader.java:58)
W/System.err:     at android.serialport.SerialPortFinder.getDrivers(SerialPortFinder.java:71)

**Comment by grubberbin** [comment]
权限问题啊

**Comment by chuncainiao** [comment]
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
这两个权限都已经添加了呀

**Comment by Mr-Jiang** [comment]
SE-Linux权限，需要改系统.te文件
