### ISSUE TITLE
关闭串口闪退了

### ISSUE THREAD

**Issue by TonyEasy** [kongqw/KqwSerialPortDemo#8]

**Comment by kongqw** [comment]
有log吗，最新版本已经修复了呀。

**Comment by TonyEasy** [comment]
我是在Activity开启，在onDestory时调用SerialPortManager.getInstance().closeSerialPort();日志是这些，
      java.lang.NoSuchFieldError: no field with name='mFd' signature='Ljava/io/FileDescriptor;' in class Lcom/kongqw/serialportlibrary/b;
     at com.kongqw.serialportlibrary.SerialPort.close(Native Method)
     at com.kongqw.serialportlibrary.b.b(SourceFile:96)

**Comment by kongqw** [comment]
您是如何使用的？导入Library 还是 gradle 导入？
`SerialPortManager.java` 有改过 `FileDescriptor` 变量名 `mFd` 吗

**Comment by TonyEasy** [comment]
我导入的Library，没有修改这个的变量名，唯一的改动就是改成了单例模式，可以加下我的QQ吗？1245793728请教你一下

**Comment by kongqw** [comment]
Library， 不排除是您导入的问题或者修改了什么内容，可以先尝试一下gradle 导入，判断下是否是库的问题。

**Comment by TonyEasy** [comment]
好的 ，我试一下

**Comment by kongqw** [comment]
@TonyEasy 结果如何？如果gradle导入仍然有问题，请reopen issue

**Comment by Wxianpeng** [comment]
混淆之后，关闭串口也是闪退 ， 报错一样

**Comment by MarcoJF888** [comment]
也是关闭串口的时候报错

      if (null != mFd) {
            close();
            mFd = null;
        }

这个close这里

567 2658-2691/? E/art: JNI DETECTED ERROR IN APPLICATION: fid == null
2020-05-22 11:39:11.567 2658-2691/? E/art:     in call to GetObjectField
2020-05-22 11:39:11.567 2658-2691/? E/art:     from void com.kongqw.serialportlibrary.SerialPort.close()
2020-05-22 11:39:11.567 2658-2691/? E/art: "Timer-2" prio=5 tid=18 Runnable
2020-05-22 11:39:11.567 2658-2691/? E/art:   | group="main" sCount=0 dsCount=0 obj=0x12f2fca0 self=0xb16ac600
2020-05-22 11:39:11.567 2658-2691/? E/art:   | sysTid=2691 nice=0 cgrp=default sched=0/0 handle=0xb2ba6920
2020-05-22 11:39:11.567 2658-2691/? E/art:   | state=R schedstat=( 1653461 1101693 8 ) utm=0 stm=0 core=3 HZ=100
2020-05-22 11:39:11.567 2658-2691/? E/art:   | stack=0xb2aa4000-0xb2aa6000 stackSize=1038KB
2020-05-22 11:39:11.567 2658-2691/? E/art:   | held mutexes= "mutator lock"(shared held)
2020-05-22 11:39:11.567 2658-2691/? E/art:   native: #00 pc 0034f0ad  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiP12BacktraceMapPKcPNS_9ArtMethodEPv+128)
2020-05-22 11:39:11.567 2658-2691/? E/art:   native: #01 pc 0032f96d  /system/lib/libart.so (_ZNK3art6Thread9DumpStackERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEEbP12BacktraceMap+632)
2020-05-22 11:39:11.567 2658-2691/? E/art:   native: #02 pc 00238381  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+1188)
2020-05-22 11:39:11.567 2658-2691/? E/art:   native: #03 pc 002393db  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+66)
2020-05-22 11:39:11.567 2658-2691/? E/art:   native: #04 pc 0026fad3  /system/lib/libart.so (_ZN3art3JNI14GetObjectFieldEP7_JNIEnvP8_jobjectP9_jfieldID+514)
2020-05-22 11:39:11.567 2658-2691/? E/art:   native: #05 pc 00000b67  /system/priv-app/rktools/rktools.apk (???)
2020-05-22 11:39:11.567 2658-2691/? E/art:   native: #06 pc 0003996f  /data/dalvik-cache/arm/system@priv-app@rktools@rktools.apk@classes.dex (Java_com_kongqw_serialportlibrary_SerialPort_close__+74)
2020-05-22 11:39:11.567 2658-2691/? E/art:     at com.kongqw.serialportlibrary.SerialPort.close(Native method)
2020-05-22 11:39:11.567 2658-2691/? E/art:     at com.intelligym.rk3288tools.device.b.a.a(SerialPortManager.java:107)
2020-05-22 11:39:11.567 2658-2691/? E/art:     at com.intelligym.rk3288tools.device.b.b.f.l(XQTreadmillSerialPort.java:431)
2020-05-22 11:39:11.567 2658-2691/? E/art:     at com.intelligym.rk3288tools.device.b.b.f.i(XQTreadmillSerialPort.java:425)
2020-05-22 11:39:11.568 2658-2691/? E/art:     at com.intelligym.rk3288tools.activity.factory.FactoryXqTreadmillActivity$1.run(FactoryXqTreadmillActivity.java:201)
2020-05-22 11:39:11.568 2658-2691/? E/art:     at java.util.TimerThread.mainLoop(Timer.java:555)
2020-05-22 11:39:11.568 2658-2691/? E/art:     at java.util.TimerThread.run(Timer.java:505)
